### ISSUE TITLE
Make project deployable on cloud service

### ISSUE THREAD

**Issue by Vunovati** [Vunovati/uskoci#1]
Cloudbees and heroku

**Comment by Vunovati** [comment]
Komunicirajmo ubuduce o featurima preko ovakvih issua na githubu. Btw ovo pisem sa github appa za android :)

**Comment by Ollienntsh** [comment]
Projekt se sada može deployati na Heroku pomoću mini webapp JAR aplikacije koja je sada uključena u glavni pom.xml, te se poziva pomoću Herokuovog Procfile-a. Još uvijek ima nekih problema koji se tiču inicijalizacije Websocketa (koji pak radi na lokalnom serveru). Njih ćemo ubrzo riješiti.

**Comment by Ollienntsh** [comment]
Znači, zasad je disfunkcionalna verzija na http://uskoci.herokuapp.com/

**Comment by Ollienntsh** [comment]
Nadalje sam čitao i čini se da je stvar u tome što Heroku u svakom slučaju nije još spreman za Websockete po defaultu. Jedina od alternativa ako ćemo koristit Heroku (a volio bih) je da iskoristimo [Pusher](http://pusher.com/) add-on (već sam ga stavio na uskoci app) koji u pozadini koristi Websocket. Osim Pushera, moguće je koristiti i Socket.IO: https://devcenter.heroku.com/articles/using-socket-io-with-node-js-on-heroku/

**Comment by Ollienntsh** [comment]
Probat ću sutra rewriteat jQuery aplikaciju da koristi Socket.IO umjesto Atmosphere socketa.

**Comment by Vunovati** [comment]
Sad radi sa cloudbeesima
