### ISSUE TITLE
Pregled bodova igrača po skupinama

### ISSUE THREAD

**Issue by kilame** [Vunovati/uskoci#11]
Vladek,

Molim te implementaciju dohvata podataka o trenutnom stanju igrača.
Struktura po igraču bi trebala sadržavati:
Ukupan broj bodova
Broj drveta i obavijest o uključenju modifikatora
Broj oružja i obavijest o uključenju modifikatora
Broj hrane i obavijest o uključenju modifikatora
Broj zalata i obavijest o uključenju modifikatora
Broj dodatnih (nedefiniranih bodova)
Broj karata u ruci [već napravljeno]
Naziv igrača

**Comment by Vunovati** [comment]
Izvolite, dodano. Zaboravio sam dodati i modifikator, ali se baci na iskorištavanje ovog što imaš sada ...

**Comment by Vunovati** [comment]
Rješeno još davno
