### ISSUE TITLE
Problem sinkronizacije koda

### ISSUE THREAD

**Issue by morpheus161186** [Vunovati/uskoci#21]
Dakle, kontroliranje koja verzija koda se pusha na master. Sadašnji prijedlog je da Vladimir kontrolira push na master (i samo on ima tu mogućnost).

**Comment by Vunovati** [comment]
Updateao sam development workflow wiki:
https://github.com/Vunovati/uskoci/wiki/Development-Workflow

Ukratko proces bi išao ovako:
Čovjek developira feature na svojoj vlastitoj lokalnoj grani (nipošto master). Kad je gotov pusha granu na GitHub (origin). Nakon toga radi pull request. Ako je radio promjene na frontendu (tu mislim na CSS, HTML, JS) radi pull requst prema Anti, ako je radio promjene na backendu radi pull requst prema meni. Kad se napravi pull request automatski se pokreću testovi na našem CI-u te se svi obavještavamo da li prolazi svi testove. Kod se reviewa i ako je sve ok merga s masterom. Ovo mi se čini kao sigurnije rješenje za situacije kao ona neki dan kad smo imali zajeb u komunikaciji jer dodaje još dva buffera: CI i čovjeka koji provjerava/merga kod. Vatavuk mi je rekao da mu je sad bed išta pushati a to definitvno nije poanta :) pa će se na ovaj način svi manje bojati da nešto ne sjebu pri pushu.

**Comment by morpheus161186** [comment]
\o/
Držat ćemo se ovoga.

2012/10/15 Vladimir Adamić notifications@github.com

> Updateao sam development workflow wiki:
> https://github.com/Vunovati/uskoci/wiki/Development-Workflow
> 
> Ukratko proces bi išao ovako:
> Čovjek developira feature na svojoj vlastitoj lokalnoj grani (nipošto
> master). Kad je gotov pusha granu na GitHub (origin). Nakon toga radi pull
> request. Ako je radio promjene na frontendu (tu mislim na CSS, HTML, JS)
> radi pull requst prema Anti, ako je radio promjene na backendu radi pull
> requst prema meni. Kad se napravi pull request automatski se pokreću
> testovi na našem CI-u te se svi obavještavamo da li prolazi svi testove.
> Kod se reviewa i ako je sve ok merga s masterom. Ovo mi se čini kao
> sigurnije rješenje za situacije kao ona neki dan kad smo imali zajeb u
> komunikaciji jer dodaje još dva buffera: CI i čovjeka koji provjerava/merga
> kod. Vatavuk mi je rekao da mu je sad bed išta pushati a to definitvno nije
> poanta :) pa će se na ovaj način svi manje bojati da nešto ne sjebu pri
> pushu.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Vunovati/uskoci/issues/21#issuecomment-9460022.

## 

Ivan Petković
Mob: +385 99 2441 253
