### ISSUE TITLE
proučiti Twitter bootstrap

### ISSUE THREAD

**Issue by morpheus161186** [Vunovati/uskoci#34]
Potrebno proučiti koliko je teško dignuti site pomoću Twitter bootstrap i koji su potrebni dodatni resursi (aka grafičar).

Ovo će se koristiti za one pager koji će se postaviti kad bude gotov MVP.

Tino je support.

**Comment by Vunovati** [comment]
Mogu vam napravit neki demo page kao okvir za one pager. Već sam radio s tim. Uglavnom uzmite u obzir da je bootstrap pisan u LESS-u objektno orjenitanim sylesheetovima koji se kompajliraju u CSS. Naravno za kompilaciju je potreban ruby :P

**Comment by morpheus161186** [comment]
Moze. Thx

Ivan Petković
Mob: +385 99 2441 253

**Comment by Vunovati** [comment]
https://dl.dropbox.com/u/4067171/uskoci-bootstrap/bootstrap/index.html
