### ISSUE TITLE
Igra zapela

### ISSUE THREAD

**Issue by morpheus161186** [Vunovati/uskoci#59]
Povukao sam kartu, odigrao sam resurs, duplikator resursa (karta obavijesti) te nakon toga kliknuo sljedeći igrač i igra je zapela.
Kliknuo sam nakon nekog vremena sljedeći igrač i nije igra prebacila na sljedećeg igrača.

**Comment by morpheus161186** [comment]
Opet mi je igra zapela nakon što sam pokušao igrati drugi event (koji ispravno nije dopustila i napisala poruku).

**Comment by Vunovati** [comment]
Daj nam točne korake da reproduciramo to. Kolko si turnova odigrao?

**Comment by morpheus161186** [comment]
U prvom sluèaju sam u prvom potezu odmah zapeo poku¹avajuæi izvesti opisano.
U drugom sluèaju je igra zapela na treæem krugu. Htio sam testirati ¹to se
dogaða kad netko doðe do 25 i dopu¹ta li igra vi¹e od 25 bodova (ne bi
smjela).

2012/11/12 Vladimir Adamiæ notifications@github.com

> Daj nam toène korake da reproduciramo to. Kolko si turnova odigrao?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Vunovati/uskoci/issues/59#issuecomment-10301982.

## 

Ivan Petkoviæ
Mob: +385 99 2441 253

**Comment by Vunovati** [comment]
Mislim da bi sad trebalo biti popravljeno.

**Comment by morpheus161186** [comment]
Ok, provjerim pa javim. 

Ivan Petković
Mob: +385 99 2441 253
