### ISSUE TITLE
mogućnost igranja resursa i duplikatora resursa

### ISSUE THREAD

**Issue by morpheus161186** [Vunovati/uskoci#60]
Igrač može igrati ili resurs ili duplikator resursa, ali nikako oboje (što sam uspio).

**Comment by Vunovati** [comment]
Nisam siguran za taj bug, nisam uspio reproducirati. Je li moguće da je kriva karta bila nacrtana jer se pojavljuje krivi artwork na kartama? jedino u što se možeš pozdat kod testiranja je ime koje se prikaže iznad karte kad hoveraš iznad nje

**Comment by morpheus161186** [comment]
ovo je stari bug
