### ISSUE TITLE
Krivi ispis poruka u gornjem dijelu ekrana

### ISSUE THREAD

**Issue by morpheus161186** [Vunovati/uskoci#66]
Given - Igrač 1 na potezu
When - Igrač 2/3/4 pokuša nešto odigrati na što nema pravo
Then - Ispisana poruka o grešci u gornjem ekranu je vidljiva svim igračima (što nije slučaj ukoliko je odigrana sipravna akcija)

Prioritet: Low

**Comment by Vunovati** [comment]
Ovo treba ovako riješiti:

Kad dobiješ game controller message sa errorom, pogledaj zadnji action. Ako je u actionu tvoj player id ispiši error. Inače ne ispisuj ništa
