### ISSUE TITLE
Igrač uspije povuči kartu iako nije nejgov potez

### ISSUE THREAD

**Issue by morpheus161186** [Vunovati/uskoci#69]
Given - Igrač nije na potezu
When - Pokuša povući kartu
Then - dobije poruku o nemogućnosti povlačenja karte

+

Given - igrač koji je na potezu 
When - povuče kartu
Then -  igrač koji je na potezu dobije kartu i igrač koji nije na potezu dobije kartu

Priority: High

**Comment by morpheus161186** [comment]
S time da kad je igrač predao potez, karta se igraču koji nije na potezu makla iz ruke...
Ali ne uvijek. Reproduciranje buga nije reporduciralo opisano nestajanje ilegalne karte.

**Comment by Vunovati** [comment]
Dobar bug find :), 
ali nisi dobro opisao:
Given - igrač koji nije na potezu je probao povuči kartu prije nego je igrač koji je na potezu povukao
When - player na potezu povuče kartu
then -obojica je dobiju
