### ISSUE TITLE
Ne radi next turn

### ISSUE THREAD

**Issue by morpheus161186** [Vunovati/uskoci#8]
Ne radi svaki put next turn bottun

**Comment by Vunovati** [comment]
Jesi li primjetio neki uzorak u tome? Nisam uspio reproducirat bug ...

**Comment by morpheus161186** [comment]
Pokrenuo sam bio samo jednog igraca i onda se ulogirao u drugog, nakon toga
si se ti ulogurao u istoga.
Budem probao reproducirati bug.

Srdaèan pozdrav,

Ivan Petkoviæ
Mob: +385 99 2441 213

On 7. 10. 2012., at 14:13, "Vladimir Adamiæ" notifications@github.com
wrote:

Jesi li primjetio neki uzorak u tome? Nisam uspio reproducirat bug ...

## 

Reply to this email directly or view it on
GitHubhttps://github.com/Vunovati/uskoci/issues/8#issuecomment-9207437.
